spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/productServicexx?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  sql:
    init:
      mode: always
