spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventoryService?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  sql:
    init:
      mode: always 
